# Kubernetes settings
replicaCount: 0

# Environment settings
environment: staging-eu2

# Application settings
userInterfaceTheme: "dark"
cacheSize: "1024kb"
gpuEnabled: "1"
pageLimit: "25"
sorting: "Ascending"
nBuckets: "42"
